export const LATEST_REPOSITORIES_REQUEST: string = 'LATEST_REPOSITORIES_REQUEST';
export const LOCAL_NUMBER_OF_PER_PAGE: string = 'LOCAL_NUMBER_OF_PER_PAGE';
export const REPOSITORIES_LOCAL_NUMBER_OF_PAGE: string = 'LOCAL_NUMBER_OF_PAGE';
export const REPOSITORIES_SORT_OPTION: string = 'SORT_OPTION';
export const REPOSITORIES_ORDER_OPTION: string = 'ORDER_OPTION';
